apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.6
          ports:
            - containerPort: 6379
          command:
            - redis-server
          args:
            - --requirepass
            - admin
  replicas: 1
  selector:
    matchLabels:
      app: redis
