apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortify-search
spec:
  template:
    metadata:
      name: shortify-search
      labels:
        app: shortify-search
    spec:
      containers:
        - name: shortify-search
          image: shortify-search:0.0.1
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: shortify-search-config-map
  replicas: 3
  selector:
    matchLabels:
      app: shortify-search
